# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: CloutPool
            image:
        nav:
            - item_name: About
              item_url: 'https://chainterra.github.io/BTCLT-Guide/about/'
            - item_name: Pre-reqs
              item_url: 'https://chainterra.github.io/BTCLT-Guide/prereqs/'
            - item_name: CloutPool
              item_url: 'https://chainterra.github.io/BTCLT-Guide/cloutpool/'
            - item_name: Mining Setup
              item_url: 'https://chainterra.github.io/BTCLT-Guide/mining-setup/'
            - item_name: Further Information
              item_url: 'https://chainterra.github.io/BTCLT-Guide/information/'     
    footer:
        content:
            logo:
                text: CloutPool
                image:
            copyright: Copyright &copy; 2021. - Andrew Magdy Kamal, ChainTerra <br>All rights reserved.
        social_list:
            - network_name: facebook
              profile_url: 'https://www.facebook.com/hashtag/CloutPool'
            - network_name: twitter
              profile_url: 'https://twitter.com/hashtag/CloutPool?src=hashtag_click'
            - network_name: instagram
              profile_url: 'https://www.instagram.com/explore/tags/CloutPool'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/results?search_query=CloutPool'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
